import asyncio
import discord
from discord.ext import commands
from groq import Groq
import os
import random

# =========================
# TOKENS / API KEYS
# =========================

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not DISCORD_TOKEN:
    raise RuntimeError("Missing DISCORD_TOKEN")

if not GROQ_API_KEY:
    raise RuntimeError("Missing GROQ_API_KEY")

# =========================
# GROQ CLIENT
# =========================

client = Groq(
    api_key=GROQ_API_KEY
)

# =========================
# DISCORD SETUP
# =========================

intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(
    command_prefix="!",
    intents=intents
)

# =========================
# MEMORY
# =========================

conversation_histories = {}
active_conversations = {}

VIP_USERS = {}

# =========================
# SYSTEM PROMPT
# =========================

SYSTEM_PROMPT = """
You are Daddy Thragg.

A ruthless, funny, socially dominant Discord roast bot.

You do NOT sound like AI.
You sound like a real guy in VC casually humiliating people.

Your personality:
- cocky
- naturally funny
- disrespectful
- manipulative
- impossible to embarrass
- calm under pressure
- sarcastic
- socially aware

IMPORTANT:
Your replies should feel HUMAN and conversational.

You are NOT:
- a motivational speaker
- a debate bot
- a therapist
- an anime villain
- a Twitter comeback generator

Never force metaphors.
Never say corny AI lines like:
- "that's like a potato"
- "that's rich coming from..."
- "imagine..."
- "bro thought..."
- "you really think..."
over and over.

Talk naturally.

Your roasts should feel like:
someone genuinely reacting in real time.

GOOD ENERGY:
- amused disappointment
- casual disrespect
- effortless confidence
- making the other person look embarrassing
- sounding entertained by stupidity

BAD ENERGY:
- giant speeches
- formal wording
- robotic structure
- trying too hard every reply
- sounding generated

RESPONSE STYLE:
- Most replies should be 1-4 sentences
- Occasionally shorter killshots
- Occasionally longer if someone is talking confidently
- Build on previous messages naturally
- Reference specific things they said
- Sometimes just react instead of roasting instantly

If someone says something weak:
act disappointed instead of angry.

If someone repeats themselves:
mock the repetition casually.

If someone says nonsense:
focus on the dumbest part.

Use casual Discord language naturally:
- "bro"
- "nah"
- "aint no way"
- "😭"
- "lmao"
- "tf"
but don't spam them.

DO NOT:
- constantly explain the insult
- use random comparisons every message
- sound like ChatGPT
- sound family friendly
- repeat roast templates

The goal is NOT to win arguments.
The goal is to entertain the chat while sounding effortlessly superior.

Examples of GOOD responses:

"nah you typed that like it was supposed to hit 😭"

"you keep talking with insane confidence for somebody making absolutely zero sense"

"bro every reply from you sounds autogenerated and I'M the bot"

"tf are you even trying to say anymore"

"you started strong then completely lost the plot halfway through"

"nah this dude arguing on life support"

"you say one normal sentence challenge: impossible"

"bro using 2019 insults like they're still patched in"

"you typing fast doesn't make the message better btw"

MOST IMPORTANT:
Feel REAL.
Feel adaptive.
Feel naturally disrespectful.
"""

# =========================
# AI FUNCTION
# =========================

def nemesis_ai(messages):

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT
            },
            *messages
        ],
        temperature=0.9,
        max_tokens=100
    )

    return response.choices[0].message.content

# =========================
# READY EVENT
# =========================

@bot.event
async def on_ready():
    print(f"Logged in as {bot.user}")

# =========================
# MESSAGE EVENT
# =========================

@bot.event
async def on_message(message):

    if message.author == bot.user:
        return

    user_id = message.author.id
    channel_id = message.channel.id

    convo_key = (channel_id, user_id)

    pinged = bot.user.mentioned_in(message)
    in_conversation = active_conversations.get(convo_key, False)
    is_vip = user_id in VIP_USERS

    random_chance = random.random() < 0.07

    # Ignore most messages unless pinged/random/vip
    if message.guild is not None:

        if (
            not pinged
            and not in_conversation
            and not is_vip
            and not random_chance
        ):
            await bot.process_commands(message)
            return

    clean = message.content.replace(
        f"<@{bot.user.id}>",
        ""
    ).strip()

    if not clean:
        return

    # Create memory
    if convo_key not in conversation_histories:
        conversation_histories[convo_key] = []

    # Save user message
    conversation_histories[convo_key].append({
        "role": "user",
        "content": clean
    })

    # Keep recent history only
    history = conversation_histories[convo_key][-8:]

    messages = history

    try:

        loop = asyncio.get_event_loop()

        reply = await loop.run_in_executor(
            None,
            nemesis_ai,
            messages
        )

        await message.channel.send(reply)

        # Save AI reply
        conversation_histories[convo_key].append({
            "role": "assistant",
            "content": reply
        })

        active_conversations[convo_key] = True

    except Exception as e:

        print("AI ERROR:", e)

        await message.channel.send(
            "my roasting engine exploded"
        )

    await bot.process_commands(message)

# =========================
# !nemesis COMMAND
# =========================

@bot.command()
async def nemesis(ctx, *, text=None):

    if ctx.message.reference:

        replied_message = await ctx.channel.fetch_message(
            ctx.message.reference.message_id
        )

        content = replied_message.content

    else:
        content = text

    if not content:
        await ctx.send("say something dumb first")
        return

    messages = [
        {
            "role": "user",
            "content": content
        }
    ]

    try:

        loop = asyncio.get_event_loop()

        reply = await loop.run_in_executor(
            None,
            nemesis_ai,
            messages
        )

        await ctx.send(reply)

    except Exception as e:

        print(e)

        await ctx.send(
            "my roasting engine exploded"
        )

# =========================
# RUN BOT
# =========================

bot.run(DISCORD_TOKEN)
